/**
 * 21-DAY MENTAL RESILIENCE PROGRAM
 * Designed for DrMindit: High-Performance Professionals
 */

const ResilienceProgramData = [
    {
        day: 1,
        id: 'res-d1',
        title: 'Grounding the Mind',
        theme: 'Nervous System Reset',
        duration: 34,
        breathing_pattern: 'Tactical Box Breathing (4-4-4-4)',
        meditation_focus: 'Physical anchoring and cognitive distancing',
        script: [
            // [0:00] Brain-Heart Coherence
            { type: 'speak', text: 'Welcome to Day One of DrMindit’s Resilience Training. This is a space for high-stakes professionals to find a different kind of strength.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Sit upright. Spine tall but not rigid. Feet flat on the floor.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Place your right hand on your heart. Your left hand on your belly. Feel the warmth of your hands.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Focus your attention on the center of your chest. Breathe into that space. Imagine your breath flowing in and out of your heart.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bring to mind someone or something you feel genuine appreciation for. Feel that appreciation as a physical sensation in your chest.' },
            { type: 'pause', duration: 20 },

            // [2:00] Tactical Breathwork
            { type: 'speak', text: 'We now move to Box Breathing. A technique used by elite performers to maintain composure under pressure.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Exhale all the air from your lungs. Prepare to inhale.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale through the nose for four... one... two... three... four. Hold the breath... one... two... three... four. Exhale through the mouth... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Continue this box at your own count. In. Hold. Out. Hold. Six minutes of dedicated focus starts now. I will notify you when we finish.' },
            { type: 'pause', duration: 360 }, // 6 mins of silence for breathing
            { type: 'speak', text: 'Final round. Deepest inhale. Controlled hold. Longest exhale.' },
            { type: 'pause', duration: 10 },

            // [10:00] Bhramari Pranayama
            { type: 'speak', text: 'Now, we engage the Vagus nerve through vibration. Bhramari. The humming breath.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Inhale deeply through the nose. On the exhale, keep your lips closed and make a steady humming sound. Like a bee.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Feel the vibration in your skull. Let it dissolve the mental noise. Continue for three minutes.' },
            { type: 'pause', duration: 160 },

            // [13:00] Guided Meditation
            { type: 'speak', text: 'The body is regulated. The mind is ready. Visualize your thoughts as data points on a screen. They are moving fast. Demanding. Urgent.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Now, mentally step back from the screen. You are not the data. You are the observer of the data.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Feel the weight of your body pressing into the seat. That weight is your anchor. Even if the data on the screen is chaotic, the anchor is stable. Stay with this feeling of grounded awareness.' },
            { type: 'pause', duration: 600 }, // 10 mins meditation pause
            { type: 'speak', text: 'Return your awareness to the room. Resilience is not the absence of stress. It is the ability to ground yourself in the midst of it.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. Carry this ground with you. You are ready.' }
        ]
    },
    {
        day: 2,
        id: 'res-d2',
        title: 'Relaxing the Body',
        theme: 'Nervous System Reset',
        duration: 34,
        breathing_pattern: 'Tactical Box Breathing (4-4-4-4)',
        meditation_focus: 'Somatic release and tension scanning',
        script: [
            { type: 'speak', text: 'Welcome to Day Two. Today we focus on the somatic experience of resilience. Relaxing the body is the fastest way to clear a high-performance mind.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Find your seat. Roll your shoulders back and down. Place your hand on your heart. Connect with the rhythm. Breathe in... imagine the breath softening your chest.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Moving into tactical box breath. Exhale fully.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 }, // 6 mins breathing
            { type: 'speak', text: 'Final round. Inhale depth. Hold peace. Exhale tension.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your shoulders and neck. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 }, // 3 mins bhramari
            { type: 'speak', text: 'The resonance has softened the edges. We will now scan the body for hidden stress. Start at your jaw. Is it tight? Let it unhinge.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Move to your eyes. Softening. Your shoulders... ice melting into water. Notice your belly... let it go. Scan down your arms... to your fingertips. Scan down your legs... to your toes.' },
            { type: 'pause', duration: 600 }, // 10 mins meditation
            { type: 'speak', text: 'You are now in a state of physiological rest. Resilience is built in the rest, as much as in the effort. Reflection: Where was the most tension hiding?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. Walk with ease.' }
        ]
    },
    {
        day: 3,
        id: 'res-d3',
        title: 'Calming Stress Response',
        theme: 'Nervous System Reset',
        duration: 34,
        breathing_pattern: 'Tactical Box Breathing (4-4-4-4)',
        meditation_focus: 'De-escalating acute physiological stress triggers',
        script: [
            { type: 'speak', text: 'Welcome to Day Three. We are building the skill of real-time stress de-escalation. In your role, stress is inevitable, but your response is optional.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Straighten your posture. Place your hand over your heart. Breathe as if you are breathing through your chest. Imagine a cooling light entering your heart.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Tactical Box Breath. Your physiological reset button. Exhale fully.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Deep inhale. Still hold. Complete exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Resonant hum. Direct the vibration to your throat and solar plexus. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'Your system is now primed for regulation. Think of a moment today where you felt your stress alarm go off. Notice where that sensation lives in your body.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Breathe into that spot. Imagine the air is cool... silver... calming. You are telling your brain: I hear the alarm, the message is received, you can turn it off now.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You are the master of your response. This internal stability is your greatest professional asset. Reflection: What was your primary physical stress signal?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are steady.' }
        ]
    },
    {
        day: 4,
        id: 'res-d4',
        title: 'Present Moment Awareness',
        theme: 'Nervous System Reset',
        duration: 34,
        breathing_pattern: 'Box Breathing (4-4-4-4)',
        meditation_focus: 'Anchoring in sensory reality to stop rumination',
        script: [
            { type: 'speak', text: 'Welcome to Day Four. Today is about the power of Now. Rumination is the enemy of performance. Presence is the cure.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Find your center. Hand on heart. Inhale slow and deep. Connect your brain to your heart beat. There is only the sensation of this breath.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Use the breath to anchor your mind to the second. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Pure awareness in every phase.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your ears and eyes. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'The resonance has cleared the field. Open your sensory awareness. Notice what you hear, what you feel. Focus on the exact point where breath enters your nose.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'If your mind drifts to story mode, simply label it Thinking and return to the sensation. The more you return, the stronger you become.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'The Now is always available to you. Whenever you feel overwhelmed today, return to one breath. Reflection: What sense brought you back most quickly?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. Be here now.' }
        ]
    },
    {
        day: 5,
        id: 'res-d5',
        title: 'Releasing Mental Noise',
        theme: 'Nervous System Reset',
        duration: 34,
        breathing_pattern: 'Box Breathing (4-4-4-4)',
        meditation_focus: 'Brain-sweep and thought detachment',
        script: [
            { type: 'speak', text: 'Welcome to Day Five. Your mind is like a workspace. Sometimes, it gets cluttered. Today, we clear the desk.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Sit tall. Hand on heart. Inhale... feel the ribcage expand. Exhale... shoulders drop. Let the heart-brain bridge become a filter.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. The rhythm is the broom that sweeps the mind. Exhale empty.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Deepest sweep. Complete release.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to the very center of your brain. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'The desk is clear. Now we manage the incoming data. Visualize a stream of water. Every thought is a leaf on that stream. Watch them float by.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Do not jump into the water to grab them. Just stay on the bank. You are practicing meta-cognition. Thinking about your thinking.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'Your mind is now a clean, efficient workspace. Carry this clarity into your first task today. One leaf at a time. Reflection: Which thought was the stickiest today?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. Mind is clear.' }
        ]
    },
    {
        day: 6,
        id: 'res-d6',
        title: 'Building Calm Focus',
        theme: 'Nervous System Reset',
        duration: 34,
        breathing_pattern: 'Box Breathing (4-4-4-4)',
        meditation_focus: 'Pre-frontal cortex activation and sustained attention',
        script: [
            { type: 'speak', text: 'Welcome to Day Six. Today, we sharpen the instrument of your attention. Focus is not about effort. It’s about the absence of distraction.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Spine straight. Hand on heart. Imagine a beam of light connecting your heart to your forehead. Steady. Unwavering. Powerful.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. The foundation of professional focus. Exhale all the way out.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Total mastery of the breath.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to the space between your eyebrows. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'The frequency is set. Visualize a single, tiny point of brilliant white light. Every ounce of your awareness is now on that point.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'High performance comes from this Effortless Effort. You are the light. You are the focus.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You have trained your mind to stay. This stamina will serve you in your most challenging moments today. Reflection: How long did you hold the point?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. Stay locked in.' }
        ]
    },
    {
        day: 7,
        id: 'res-d7',
        title: 'Weekly Integration',
        theme: 'Nervous System Reset',
        duration: 34,
        breathing_pattern: 'Combined techniques',
        meditation_focus: 'Consolidating the baseline of calm',
        script: [
            { type: 'speak', text: 'Welcome to Day Seven. The completion of your first week. Resetting the baseline of your power.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Find your deepest seat. Both hands on your heart. Breathe deeply. Feel the strength of the foundation you’ve built this week. You are integrated.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. The tool that now feels like a natural part of you. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. The breath of a high-performance professional.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Let the vibration fill your entire torso. Crown to tailbone. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'The integration begins. Recall the grounding, the release, the de-escalation. Feel all these states merging into one Resilient Baseline.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'You don’t need to do these things anymore. They are becoming who you are. Moving, responding, leading from regulated power.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'Week One is complete. Your nervous system is reset. Next week, we move into Emotional Regulation. Reflection: What was the most impactful moment?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You have transformed.' }
        ]
    },
    // WEEK 2: Emotional Regulation
    {
        day: 8,
        id: 'res-d8',
        title: 'Emotional Awareness',
        theme: 'Emotional Regulation',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Identifying subtle emotional triggers',
        script: [
            { type: 'speak', text: 'Welcome to Week Two. We are moving from resetting the system to regulating the self. Resilience is about how you relate to your emotions under pressure.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Find your posture. Upright. Open. Hand on heart. Breathe in... feel the heart beating against your palm. Acknowledge any emotions you’re carrying right now. Name them silently.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. The tool that allows you to pause before you react. Exhale fully.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Deep inhale. Stable hold. Controlled exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your heart and throat. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'Focus your attention inward. Imagine your emotional state is like the weather. The weather doesn’t change the mountain. You are the mountain.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Notice a sensation. Label it as an emotion. By labeling it, you are moving it from your emotional center to your thinking center. You are gaining authority.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You are the observer of the weather. Carry this observant stance into your next interaction. Reflection: What was the weather like today?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are observing.' }
        ]
    },
    {
        day: 9,
        id: 'res-d9',
        title: 'Stress Recovery',
        theme: 'Emotional Regulation',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Post-crisis regulation and cortisol flushing',
        script: [
            { type: 'speak', text: 'Welcome to Day Nine. Peak performance requires peak recovery. Today, we focus on clearing the residue of high-stress events.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Sit comfortably. Support your spine. Hand on heart. Inhale... imagine the breath is a cool stream. Exhale... letting go of lingering weight.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Use the exhale to flush residual chemicals. Exhale completely.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Deepest inhale. Purest hold. Longest flush.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your stomach and lower back. Clearing stress memory. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'The system is flushing. Imagine standing under a waterfall of warm, golden light. It washes away jagged edges, sharp memories, lingering urgency.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'You are becoming lighter with every breath. Recovery is not a luxury. It is a prerequisite for excellence. Reflection: Where does your body hold the last bit?' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You have completed the stress cycle. Your body and mind are ready for what comes next.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are recovered.' }
        ]
    },
    {
        day: 10,
        id: 'res-d10',
        title: 'Letting Go',
        theme: 'Emotional Regulation',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Releasing resentment and perceived failures',
        script: [
            { type: 'speak', text: 'Welcome to Day Ten. Resilience is not just about what you can handle. It is also about what you can put down.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Straighten your spine. Hand on heart. Inhale... feel the heart beating. Exhale... imagine tethers being cut. Today, we practice the strength of letting go.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. The pause is where the release happens. Exhale completely.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Purest inhale. Empty hold. Total release.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to the base of your skull. Shaking loose the grip of "should have". Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'The resonance has cleared the air. Visualize yourself holding a heavy stone—a perceived failure. Now, simply open your hand. Watch it fall.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'You are not defined by what you didn’t do perfectly. You are defined by your capacity to learn. Breathe into the space where the weight used to be.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'Your hands are now empty. Empty hands can build something new. Reflection: What was the heaviest stone you dropped today?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are free.' }
        ]
    },
    {
        day: 11,
        id: 'res-d11',
        title: 'Inner Stability',
        theme: 'Emotional Regulation',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Building an internal locus of control',
        script: [
            { type: 'speak', text: 'Welcome to Day Eleven. Today we build your internal fortress. In your role, the world is unpredictable, but your internal state can be a constant.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Hand on heart. Feel the solidity of your character. Connect your brain to this internal center. It is deep. It is stable. It is yours.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Creating the stable rhythm of the center. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Unshakable inhale. Solid hold. Steady exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to the center of your chest. Creating a barrier around your core. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'You are centered. Visualize yourself as a massive oak tree. Roots deeper than any storm can reach. The branches may sway, but the trunk is still.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Feel that same stability in your spine. When chaos happens, you watch it. You choose the response. This is your internal locus of control.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You are unshakable. When the world spins, you are the still point. Reflection: What part of your body feels most like a pillar?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are a foundation.' }
        ]
    },
    {
        day: 12,
        id: 'res-d12',
        title: 'Strength Under Pressure',
        theme: 'Emotional Regulation',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Maintaining EQ during active conflict',
        script: [
            { type: 'speak', text: 'Welcome to Day Twelve. Strength is not just about holding your ground. It is about holding your composure when the ground is shaking.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Imagine you are wearing a suit of armor made of calm. Hand on heart. Inhale... heartbeat is steady. Strong. You are training for the moments that matter.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Tool special forces use in battle. Exhale fully.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Powerful inhale. Silent hold. Controlled exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your jaw and temples. Release the bracing. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'You are regulated and ready. Visualize a high-stakes moment at work. See yourself breathing while the world reacts. You are the calmest person in the room.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Heart steady. Voice even. You are responding with precision, not reacting with emotion. Strength is a decision made in advance.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'Strength is a habit. You have made the decision today. Reflection: What part of the vision felt most strong?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are poised.' }
        ]
    },
    {
        day: 13,
        id: 'res-d13',
        title: 'Mental Clarity',
        theme: 'Emotional Regulation',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Seeing through emotional fog',
        script: [
            { type: 'speak', text: 'Welcome to Day Thirteen. After the pressure of yesterday, we seek clarity. A leader’s job is to see what others miss.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Hand on heart. Inhale... expand awareness. Imagine your mind is a clear lens. Exhale... blowing away the dust of interpretations.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Tool that sharpens the edge of the mind. Exhale completely.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Crystalline inhale. Silent hold. Transparent exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your mid-brain. Clearing cobwebs. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'The lens is clean. Look at a complex problem you’re solving. Strip away the stories of who is to blame. Just see the data points.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'When the ego is quiet, the answer becomes obvious. Real clarity is found in the silence between thoughts. Trust the insights.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You are the observer of complexity. Reflection: What one fact became clear today?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You see.' }
        ]
    },
    {
        day: 14,
        id: 'res-d14',
        title: 'Weekly Integration',
        theme: 'Emotional Regulation',
        duration: 34,
        breathing_pattern: 'Combined',
        meditation_focus: 'Harmonizing regulation and stability',
        script: [
            { type: 'speak', text: 'Welcome to Day Fourteen. Completion of Week Two. We have moved through awareness, recovery, letting go, and strength.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Both hands on heart. Inhale resonant. You are becoming a person who regulates their own frequency. You are harmonious.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Rhythm of your regulated life. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Breath of an integrated professional.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct vibration through your whole being. Resonance of your integrated self. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'Recall the weather, the flush, the pillar. Merge them. You are a regulated system. Graceful under pressure.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Week Two is complete. You have mastered your response. Next week, we unlock your full potential: Peak Performance. Reflection: Which skill felt most natural?' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You are ready to excel.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are balanced.' }
        ]
    },
    // WEEK 3: Peak Performance
    {
        day: 15,
        id: 'res-d15',
        title: 'Cognitive Clarity',
        theme: 'Peak Mental Performance',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Reducing cognitive load and enhancing pattern recognition',
        script: [
            { type: 'speak', text: 'Welcome to Week Three. We have built the foundation. Now, we build the peak. Cognitive performance is not about thinking more. It is about thinking better.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Sit with alert presence. Hand on heart. Inhale... imagine every breath is oxygenating your pre-frontal cortex. Power. Precision. Clarity.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Creating the steady rhythm of a high-performance brain. Exhale all air.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Deepest inhale. Crystalline hold. Perfect exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to the very front of your brain. Waking up strategic centers. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'The field is clear. Visualize a complex system you manage. Nodes and connections. Watch the data flowing. Notice the point of friction.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Breathe into that node. Let your intuitive brain see the solution that logic missed. Clarity is a revelation. You see deeper patterns.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You have the Clean Slate. Carry this strategic depth into your next meeting. Reflection: What bottleneck became obvious today?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are sharp.' }
        ]
    },
    {
        day: 16,
        id: 'res-d16',
        title: 'Flow State Trigger',
        theme: 'Peak Mental Performance',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Establishing physiological conditions for deep flow',
        script: [
            { type: 'speak', text: 'Welcome to Day Sixteen. Today, we trigger Flow. Flow happens when the challenge meets your highest skill level.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Posture: Strong. Relaxed. Hand on heart. Imagine your sense of self dissolving into your sense of action. You Are the work.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Creating the baseline for effortless power. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Deepest flow. Stillest hold. Easiest exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your whole skull. bridging the hemispheres. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'You are in the zone. Recall a time when focus was absolute. Bring that feeling into your body. This is your peak state.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Imagine your next major task. See yourself entering it with easy power. No doubt. No friction. Just action. You are training the trigger.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You can access this state whenever you choose. The portal is the breath. Reflection: What did effortless power feel like?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are fluid.' }
        ]
    },
    {
        day: 17,
        id: 'res-d17',
        title: 'Deep Recovery',
        theme: 'Peak Mental Performance',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'NSDR states for rapid cognitive rejuvenation',
        script: [
            { type: 'speak', text: 'Welcome to Day Seventeen. High performance is unsustainable without high recovery. Today, we go beyond relaxation into deep rest.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Lie down or support your head. Hand on heart. Give your body permission to be completely heavy. Nothing to solve. Just receive.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Bridge to the parasympathetic depths. Soften the breath. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Softest inhale. Longest exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your spine and hips. A lullaby for your nervous system. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'You are drifting. Visualize sinking into warm blue light. Every cell in your brain is taking a power nap. Recharging. Healing.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'You are accessing the delta state. Peaceful depths. Stay here. This rest is your fuel for tomorrow’s excellence.' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'Return slowly. You are rejuvenated. You have stepped out of time for a moment. Reflection: How heavy was your body?' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are restored.' }
        ]
    },
    {
        day: 18,
        id: 'res-d18',
        title: 'Strategic Intuition',
        theme: 'Peak Mental Performance',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Accessing sub-conscious pattern recognition',
        script: [
            { type: 'speak', text: 'Welcome to Day Eighteen. Logic is essential, but intuition is the extra gear. Today, we listen to the signals logic often misses.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Spine straight as an antenna. Hand on heart. Connect with your gut feeling. Open the channel. You trust your signal.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Calming the conscious mind. Focus on the space between counts. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Receptive inhale. Still hold. Open exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration to your solar plexus. your gut brain. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'Open and receptive. Bring to mind a choice. Feel the texture of Option A. Now, Option B. Your sub-conscious knows the pattern.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Intuition is integrated experience. Trust the first quiet signal. Act with head and heart. Reflection: Which option felt expansive?' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'Your intuition is a calibrated instrument. Trust it.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You know.' }
        ]
    },
    {
        day: 19,
        id: 'res-d19',
        title: 'Sustained Excellence',
        theme: 'Peak Mental Performance',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Building cognitive stamina and purpose-driven endurance',
        script: [
            { type: 'speak', text: 'Welcome to Day Nineteen. Excellence is not a sprint. It is a marathon of sprints. Today we focus on the energy that sustains you.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Sit tall. Hand on heart. Feel the source of your motivation. Connect heart passion to brain execution. You are built for the long haul.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. The rhythmic pacing of a master. Consistent power. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Deepest inhale. Quietest hold. Infinite exhale.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Direct the vibration through your whole nervous system. Smoothing out the gears. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'A reservoir of steady energy. Visualize yourself six months from now—performing at this level with calm. Imagine a sun in your solar plexus.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Operating from abundance. Excellence is a choice made with every breath. You chose to stay regulated. Reflection: What is the fuel for your sun?' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You have the Infinite Battery. Excellence is your legacy.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You endure.' }
        ]
    },
    {
        day: 20,
        id: 'res-d20',
        title: 'Deep Recovery & Reset',
        theme: 'Peak Mental Performance',
        duration: 34,
        breathing_pattern: 'Tactical Breath',
        meditation_focus: 'Absolute stillness and systemic recalibration',
        script: [
            { type: 'speak', text: 'Welcome to Day Twenty. One day remains. Before the final graduation, we must return to zero.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Support your body. Let go of the need to be anything. Hand on heart. Simple sensation of existing. Resetting the baseline.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. Final tuning of the instrument. Focus on the Zero Point. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Deepest peace. Stillest hold. Most complete reset.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Let the vibration fade into silence. Dissolving. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'You are at the Zero Point. pure potential. No roles, no titles. Just awareness. Profound freedom. Becoming everything.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Stay in the void. Recalibrate. When you open your eyes, the world will be new. Reflection: What does Zero Point feel like?' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'You are reset. Ready for the final step.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This session is complete. You are still.' }
        ]
    },
    {
        day: 21,
        id: 'res-d21',
        title: 'Program Graduation',
        theme: 'Peak Mental Performance',
        duration: 34,
        breathing_pattern: 'Combined',
        meditation_focus: 'Final integration into the new resilient identity',
        script: [
            { type: 'speak', text: 'Welcome to Day Twenty-One. Your graduation. You have built the machine. Sit with the quiet confidence of a master.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Both hands on heart. Breathe deeply. You are not the person who started on Day One. You are a Resilient Being.' },
            { type: 'pause', duration: 20 },
            { type: 'speak', text: 'Box Breath. The rhythm you will carry into the world. Regulatory power is your default. Exhale release.' },
            { type: 'pause', duration: 3 },
            { type: 'speak', text: 'Inhale for four... one... two... three... four. Hold... one... two... three... four. Exhale... one... two... three... four. Hold empty... one... two... three... four.' },
            { type: 'pause', duration: 360 },
            { type: 'speak', text: 'Final round. Breathe with total authority.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'Bhramari hum. Final declaration of your excellence. Resonance filling the room. Inhale.' },
            { type: 'pause', duration: 5 },
            { type: 'speak', text: 'Mmmmmm.' },
            { type: 'pause', duration: 160 },
            { type: 'speak', text: 'Integration is complete. When crisis hits, you ground. When emotion rises, you regulate. When focus is needed, you excel.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This is who you are. Graduated from trying to being. DrMindit is always here. Reflection: Who will you be in the world today?' },
            { type: 'pause', duration: 600 },
            { type: 'speak', text: 'Go out and lead with your presence. You have arrived.' },
            { type: 'pause', duration: 10 },
            { type: 'speak', text: 'This program is complete. You are DrMindit.' }
        ]
    }
];

if (typeof module !== 'undefined') {
    module.exports = { ResilienceProgramData };
}
